Rework types (option 3)
dylibso/chicory pull request #244
Opened 2024-02-16 17:04 UTC by dmlloyd

* Create constants for each type ID
* Use switch statements for finding types by ID to avoid boxing overheads
* Add query methods for type characteristics
* Replace `ElementType` with `ValueType`

2024-02-16 17:49 UTC, andreaTP requested changes
I like the changes done in this direction, I would remove the `OrThrow` suffix and make the throwing methods the only and default implementation.
Since we are consolidating the API I think we can go down this path 🙂

2024-02-16 17:49 UTC, andreaTP commented on wasm/src/main/java/com/dylibso/chicory/wasm/types/ValueType.java
> +    public static ValueType forIdOrThrow(int id) {
I think that this can be the only default implementation, I would call it `forId` and make the current `forId` `private` or simply remove it, wdyt?

2024-02-16 17:49 UTC, andreaTP commented on wasm/src/main/java/com/dylibso/chicory/wasm/types/ValueType.java
> +    public static ValueType refTypeForIdOrThrow(int id) {
What about keeping only this as the default implementation for `refTypeForId` ?

2024-02-16 18:01 UTC, dmlloyd commented
Applied suggestions to not have a `null`-returning option for the get-by-ID methods.

2024-02-16 18:08 UTC, andreaTP approved these changes
This looks good to me, but I would like to have a second opinion before merging if it doesn't take too long.

cc. @bhelx @danielperano @mariofusco

2024-02-16 18:09 UTC, dmlloyd commented
Looks like there's one problem due to the non-null returning option, but the fix should be simple.

2024-02-16 18:09 UTC, andreaTP commented
(and CI should be green 😄 )

2024-02-16 18:15 UTC, dmlloyd commented
All fixed :+1:

2024-02-17 08:12 UTC, mariofusco approved these changes

2024-02-17 12:39 UTC, merged